# This is a basic workflow to help you get started with Vue s3 deployer action

name: Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Upload S3
        # You may pin to the exact commit or the version.
        # uses: shallwefootball/upload-s3-action@bcd7c2408245fd6cd19b5512a473b1a7a8b48a35
        uses: shallwefootball/upload-s3-action@v1.1.3
        with:
          # aws key id
          aws_key_id: ${{ secrets.ACCESS_KEY_ID }}
          # aws secret access key
          aws_secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
          # aws bucket name
          aws_bucket: ${{ secrets.BUCKET_NAME }}
          # directory to upload
          source_dir: .
          # destination directory for upload
          destination_dir: .
